//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLC.Scientific.Acquisition.Tools.ItineraryGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;Port=5432;User Id=postgres;Password=postgres;Database=bgr;Poolin" +
            "g=true;MinPoolSize=1;MaxPoolSize=20;ConnectionLifeTime=15;")]
        public string BgrConnectionString {
            get {
                return ((string)(this["BgrConnectionString"]));
            }
            set {
                this["BgrConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AutoCorrectDelta {
            get {
                return ((int)(this["AutoCorrectDelta"]));
            }
            set {
                this["AutoCorrectDelta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Routes")]
        public global::DLC.Scientific.Core.Geocoding.Bgr.BgrDataTypes AllowedBgrDataTypes {
            get {
                return ((global::DLC.Scientific.Core.Geocoding.Bgr.BgrDataTypes)(this["AllowedBgrDataTypes"]));
            }
            set {
                this["AllowedBgrDataTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MinSearchRadiusInMeters {
            get {
                return ((int)(this["MinSearchRadiusInMeters"]));
            }
            set {
                this["MinSearchRadiusInMeters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MaxSearchRadiusInMeters {
            get {
                return ((int)(this["MaxSearchRadiusInMeters"]));
            }
            set {
                this["MaxSearchRadiusInMeters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int DirectionBufferSize {
            get {
                return ((int)(this["DirectionBufferSize"]));
            }
            set {
                this["DirectionBufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GpsLogGap {
            get {
                return ((int)(this["GpsLogGap"]));
            }
            set {
                this["GpsLogGap"] = value;
            }
        }
    }
}
