//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QbservableProvider.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QbservableProvider.Properties.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service and/or formatterFactory arguments could not be deserialized in the new AppDomain.  Make sure that their delegates point to publicly visible members..
        /// </summary>
        internal static string CreateServiceDelegatesNotPublic {
            get {
                return ResourceManager.GetString("CreateServiceDelegatesNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query executes a void-returning method &quot;{0}&quot; on a local type &quot;{1}&quot;.  Method calls in Qbservable queries are not permitted to be executed only for their local side-effects..
        /// </summary>
        internal static string ExpressionCallLocalVoidFormat {
            get {
                return ResourceManager.GetString("ExpressionCallLocalVoidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query executes a method &quot;{0}&quot; on a local type &quot;{1}&quot; with an argument that is not available locally..
        /// </summary>
        internal static string ExpressionCallMissingLocalArgumentFormat {
            get {
                return ResourceManager.GetString("ExpressionCallMissingLocalArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query executes a method &quot;{0}&quot; on a local type &quot;{1}&quot; for which an instance is not available locally..
        /// </summary>
        internal static string ExpressionCallMissingLocalInstanceFormat {
            get {
                return ResourceManager.GetString("ExpressionCallMissingLocalInstanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A closure was not replaced while visiting its members.  This may indicate a problem with the visitor..
        /// </summary>
        internal static string ExpressionClosureBug {
            get {
                return ResourceManager.GetString("ExpressionClosureBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delegate used in the query has a non-generic anonymous return type.{0}Delegate type: {1}.
        /// </summary>
        internal static string ExpressionDelegateReturnsNonGenericAnonymousType {
            get {
                return ResourceManager.GetString("ExpressionDelegateReturnsNonGenericAnonymousType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query uses a field or property &quot;{0}&quot; on a local type &quot;{1}&quot; for which an instance is not available locally..
        /// </summary>
        internal static string ExpressionMemberMissingLocalInstanceFormat {
            get {
                return ResourceManager.GetString("ExpressionMemberMissingLocalInstanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; cannot be used in the query because it derives from type &quot;{1}&quot;, which was not specified as a known type..
        /// </summary>
        internal static string ExpressionUnknownBaseType {
            get {
                return ResourceManager.GetString("ExpressionUnknownBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; cannot be used in the query because it was not specified as a known type..
        /// </summary>
        internal static string ExpressionUnknownType {
            get {
                return ResourceManager.GetString("ExpressionUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compiler-generated type is referenced at an unsupported position in the query..
        /// </summary>
        internal static string ExpressionUnsupportedCompilerType {
            get {
                return ResourceManager.GetString("ExpressionUnsupportedCompilerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compiler-generated type is referenced as a method&apos;s generic type argument at an unsupported position in the query..
        /// </summary>
        internal static string ExpressionUnsupportedCompilerTypeAsMethodTypeArg {
            get {
                return ResourceManager.GetString("ExpressionUnsupportedCompilerTypeAsMethodTypeArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compiler-generated type is referenced as a generic type argument at an unsupported position in the query..
        /// </summary>
        internal static string ExpressionUnsupportedCompilerTypeAsTypeArg {
            get {
                return ResourceManager.GetString("ExpressionUnsupportedCompilerTypeAsTypeArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compiler-generated type was visited twice..
        /// </summary>
        internal static string ExpressionVisitedCompilerTypeTwice {
            get {
                return ResourceManager.GetString("ExpressionVisitedCompilerTypeTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client has sent a query that requires duplex communication, which is currently disabled on the server.  To enable duplex communication, specify the EnableDuplex option when creating the service..
        /// </summary>
        internal static string ProtocolDuplexSinkUnavailableForClientCallback {
            get {
                return ResourceManager.GetString("ProtocolDuplexSinkUnavailableForClientCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate duplex callback identifier..
        /// </summary>
        internal static string ProtocolDuplicateDuplexId {
            get {
                return ResourceManager.GetString("ProtocolDuplicateDuplexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duplex callback enumerator identifier is a duplicate..
        /// </summary>
        internal static string ProtocolDuplicateDuplexIdForEnumerator {
            get {
                return ResourceManager.GetString("ProtocolDuplicateDuplexIdForEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duplex callback invocation identifier is a duplicate..
        /// </summary>
        internal static string ProtocolDuplicateDuplexIdForInvoke {
            get {
                return ResourceManager.GetString("ProtocolDuplicateDuplexIdForInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duplex callback observable identifier is a duplicate..
        /// </summary>
        internal static string ProtocolDuplicateDuplexIdForObservable {
            get {
                return ResourceManager.GetString("ProtocolDuplicateDuplexIdForObservable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol expected Subscribe message but received {0} instead..
        /// </summary>
        internal static string ProtocolExpectedMessageSubscribeFormat {
            get {
                return ResourceManager.GetString("ProtocolExpectedMessageSubscribeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duplex callback identifier is invalid..
        /// </summary>
        internal static string ProtocolInvalidDuplexId {
            get {
                return ResourceManager.GetString("ProtocolInvalidDuplexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duplex callback enumerator identifier is invalid..
        /// </summary>
        internal static string ProtocolInvalidDuplexIdForEnumerator {
            get {
                return ResourceManager.GetString("ProtocolInvalidDuplexIdForEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duplex callback inovcation identifier is invalid..
        /// </summary>
        internal static string ProtocolInvalidDuplexIdForInvoke {
            get {
                return ResourceManager.GetString("ProtocolInvalidDuplexIdForInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duplex callback observable identifier is invalid..
        /// </summary>
        internal static string ProtocolInvalidDuplexIdForObservable {
            get {
                return ResourceManager.GetString("ProtocolInvalidDuplexIdForObservable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown message kind received: {0}.
        /// </summary>
        internal static string ProtocolUnknownMessageKindFormat {
            get {
                return ResourceManager.GetString("ProtocolUnknownMessageKindFormat", resourceCulture);
            }
        }
    }
}
