//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rxx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rxx.Properties.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument type for the specified RoutedEvent cannot be determined from the type of its delegate..
        /// </summary>
        internal static string CannotDetermineRoutedEventArgsType {
            get {
                return ResourceManager.GetString("CannotDetermineRoutedEventArgsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual cursor branches cannot be reset.  To reset the entire cursor, call Reset on the primary cursor object instead..
        /// </summary>
        internal static string CannotResetCursorBranch {
            get {
                return ResourceManager.GetString("CannotResetCursorBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DependencyProperty was not found on the specified DependencyObject..
        /// </summary>
        internal static string DependencyPropertyNotFound {
            get {
                return ResourceManager.GetString("DependencyPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event member&apos;s delegate has an arguments parameter that is not compatible with System.EventArgs.  Member name: {0}..
        /// </summary>
        internal static string EventIsNotCompatibleWithEventArgs {
            get {
                return ResourceManager.GetString("EventIsNotCompatibleWithEventArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event member&apos;s delegate is not compatible with System.EventHandler&lt;TEventArgs&gt;.  Member name: {0}..
        /// </summary>
        internal static string EventIsNotCompatibleWithEventHandler {
            get {
                return ResourceManager.GetString("EventIsNotCompatibleWithEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified delegate type is not compatible with the delegate type of the RoutedEvent..
        /// </summary>
        internal static string EventSubscriptionIncompatibleDelegate {
            get {
                return ResourceManager.GetString("EventSubscriptionIncompatibleDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified handler is not a compatible delegate type, ICommand or IObserver&lt;EventPattern&lt;TEventArgs&gt;&gt; object for the specified RoutedEvent..
        /// </summary>
        internal static string EventSubscriptionIncompatibleHandler {
            get {
                return ResourceManager.GetString("EventSubscriptionIncompatibleHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified observer&apos;s type argument is not compatible with the delegate type of the RoutedEvent.  Expected EventPattern&lt;TEventArgs&gt; where TEventArgs is any type that is compatible with the argument type of the RoutedEvent..
        /// </summary>
        internal static string EventSubscriptionIncompatibleObserver {
            get {
                return ResourceManager.GetString("EventSubscriptionIncompatibleObserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An in-line query cannot be parsed while the grammar is being defined..
        /// </summary>
        internal static string InlineParseNotSupported {
            get {
                return ResourceManager.GetString("InlineParseNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temporary in-line parser does not have a grammar..
        /// </summary>
        internal static string InlineParserWithoutGrammar {
            get {
                return ResourceManager.GetString("InlineParserWithoutGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the specified directory path is invalid..
        /// </summary>
        internal static string InvalidFormatDirectoryPath {
            get {
                return ResourceManager.GetString("InvalidFormatDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PairDirection value is invalid..
        /// </summary>
        internal static string InvalidPairDirectionValue {
            get {
                return ResourceManager.GetString("InvalidPairDirectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The \&quot;{0}\&quot; operation does not return System.IObservable&lt;T&gt;..
        /// </summary>
        internal static string OperationIsNotObservable {
            get {
                return ResourceManager.GetString("OperationIsNotObservable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The \&quot;{0}\&quot; operation is not synchronous..
        /// </summary>
        internal static string OperationIsNotSynchronous {
            get {
                return ResourceManager.GetString("OperationIsNotSynchronous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation \&quot;{0}\&quot; is missing input parameters.  Expected {1} but received {2}..
        /// </summary>
        internal static string OperationMissingInputParameters {
            get {
                return ResourceManager.GetString("OperationMissingInputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse cannot be called again until the current parse operation completes..
        /// </summary>
        internal static string ParseCalledWhileParsing {
            get {
                return ResourceManager.GetString("ParseCalledWhileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in parser input sequence..
        /// </summary>
        internal static string ParseExceptionMessage {
            get {
                return ResourceManager.GetString("ParseExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Source index: {2}..
        /// </summary>
        internal static string ParseExceptionMessageOverrideFormat {
            get {
                return ResourceManager.GetString("ParseExceptionMessageOverrideFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is unavailable until after Parse has been called and it has completed successfully..
        /// </summary>
        internal static string ParseNotCalledOrFailed {
            get {
                return ResourceManager.GetString("ParseNotCalledOrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser cannot move the cursor to the end of the input sequence because the current index is ahead of the latest index..
        /// </summary>
        internal static string ParserCannotMoveToEndBackward {
            get {
                return ResourceManager.GetString("ParserCannotMoveToEndBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Next property cannot be read until after Parse is called..
        /// </summary>
        internal static string ParserNextNotReady {
            get {
                return ResourceManager.GetString("ParserNextNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser does not allow new subscriptions until the current parse operation completes..
        /// </summary>
        internal static string ParseSubscribeCalledWhileParsing {
            get {
                return ResourceManager.GetString("ParseSubscribeCalledWhileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified property does not support change events..
        /// </summary>
        internal static string PropertyDoesNotSupportChangeEvents {
            get {
                return ResourceManager.GetString("PropertyDoesNotSupportChangeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified expression contains an indexer..
        /// </summary>
        internal static string PropertyExpressionContainsIndexer {
            get {
                return ResourceManager.GetString("PropertyExpressionContainsIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified expression cannot be understood as a property..
        /// </summary>
        internal static string PropertyExpressionNotUnderstood {
            get {
                return ResourceManager.GetString("PropertyExpressionNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified expression cannot be understood as a property being read from a local variable, field, another property, or a chain of fields and properties..
        /// </summary>
        internal static string PropertyExpressionOwnerNotUnderstood {
            get {
                return ResourceManager.GetString("PropertyExpressionOwnerNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified expression contains more than just fields and properties..
        /// </summary>
        internal static string PropertyExpressionTooComplex {
            get {
                return ResourceManager.GetString("PropertyExpressionTooComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner of the specified property could not be determined..
        /// </summary>
        internal static string PropertyExpresssionOwnerNotDetermined {
            get {
                return ResourceManager.GetString("PropertyExpresssionOwnerNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified property is read-only.  Property name: {0}..
        /// </summary>
        internal static string PropertyIsReadOnly {
            get {
                return ResourceManager.GetString("PropertyIsReadOnly", resourceCulture);
            }
        }
    }
}
